#!/bin/bash
set -euo pipefail
trap 'echo "ERROR: 배포 실패 (line $LINENO)" >&2' ERR

# --- 설정 ---
AWS_REGION="ap-northeast-2"
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
COMPOSE_DIR="$(cd "$(dirname "$0")" && pwd)"
SSM_PREFIX="/qfeed/prod/ai"
ENV_FILE="${COMPOSE_DIR}/.env"

# --- 인자 확인 ---
IMAGE_TAG="${1:?IMAGE_TAG가 필요합니다 (예: ./deploy.sh abc123)}"

# --- SSM에서 환경변수 조회 ---
get_ssm() {
  aws ssm get-parameter \
    --region "$AWS_REGION" \
    --name "${SSM_PREFIX}/$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text
}

echo "SSM 파라미터 조회 중..."

GPU_STT_URL=$(get_ssm "gpu-stt-url")
GPU_LLM_URL=$(get_ssm "gpu-llm-url")

echo "SSM 파라미터 조회 완료 (2개)"

# --- .env 파일 생성 ---
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh — DO NOT EDIT
ECR_REGISTRY=${ECR_REGISTRY}
IMAGE_TAG=${IMAGE_TAG}

# Environment
ENVIRONMENT=prod
AWS_REGION=${AWS_REGION}
AWS_PARAMETER_STORE_PATH=${SSM_PREFIX}

# AI Service
GPU_STT_URL=${GPU_STT_URL}
GPU_LLM_URL=${GPU_LLM_URL}
EOF

chmod 600 "$ENV_FILE"
echo ".env 파일 생성 완료"

# --- 기존 docker run 컨테이너 정리 (compose 전환 시 1회만) ---
docker stop qfeed-ai 2>/dev/null || true
docker rm qfeed-ai 2>/dev/null || true

# --- ECR 로그인 ---
aws ecr get-login-password --region "$AWS_REGION" \
  | docker login --username AWS --password-stdin "$ECR_REGISTRY"

# --- 배포 ---
docker compose -f "$COMPOSE_DIR/docker-compose.yml" pull
docker compose -f "$COMPOSE_DIR/docker-compose.yml" up -d

# --- 이전 이미지 정리 ---
docker images "${ECR_REGISTRY}/qfeed-ecr-ai" --format '{{.Tag}}' \
  | grep -v "^${IMAGE_TAG}$" \
  | xargs -I{} docker rmi "${ECR_REGISTRY}/qfeed-ecr-ai:{}" 2>/dev/null || true
docker image prune -f

# --- .env 파일 삭제 (보안) ---
rm -f "$ENV_FILE"

# --- 결과 확인 ---
echo "배포 완료: ${ECR_REGISTRY}/qfeed-ecr-ai:${IMAGE_TAG}"
docker compose -f "$COMPOSE_DIR/docker-compose.yml" ps

# --- 헬스체크 ---
echo "헬스체크 대기 중 (최대 120초)..."
for i in $(seq 1 12); do
  sleep 10
  if docker compose -f "$COMPOSE_DIR/docker-compose.yml" ps ai | grep -q "healthy"; then
    echo "✅ AI(prod) 컨테이너가 정상적으로 실행 중입니다."
    exit 0
  fi
  echo "  ... 대기 중 (${i}0초 경과)"
done
echo "❌ AI(prod) 컨테이너 실행 실패 (120초 타임아웃)" >&2
docker compose -f "$COMPOSE_DIR/docker-compose.yml" logs ai --tail 50
exit 1
