#!/bin/bash
set -euo pipefail
trap 'echo "ERROR: 배포 실패 (line $LINENO)" >&2' ERR

# --- 설정 ---
AWS_REGION="ap-northeast-2"
COMPOSE_DIR="$(cd "$(dirname "$0")" && pwd)"
SSM_PREFIX="/qfeed/dev/be"
ENV_FILE="${COMPOSE_DIR}/.env"

# --- SSM에서 Redis 비밀번호 조회 ---
get_ssm() {
  aws ssm get-parameter \
    --region "$AWS_REGION" \
    --name "${SSM_PREFIX}/$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text
}

echo "SSM 파라미터 조회 중..."
REDIS_PASSWORD=$(get_ssm "REDIS_PASSWORD")
echo "SSM 파라미터 조회 완료"

# --- .env 파일 생성 ---
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh — DO NOT EDIT
REDIS_PASSWORD=${REDIS_PASSWORD}
EOF

chmod 600 "$ENV_FILE"
echo ".env 파일 생성 완료"

# --- EC2 Name 태그 조회 (Alloy instance 레이블용) ---
EC2_NAME=$(aws ec2 describe-tags \
  --region "$AWS_REGION" \
  --filters "Name=resource-id,Values=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)" \
            "Name=key,Values=Name" \
  --query "Tags[0].Value" --output text)
export EC2_NAME
echo "EC2 Name: ${EC2_NAME}"

# --- 배포 (Alloy + Redis Exporter만, Redis 컨테이너는 user_data에서 기동) ---
docker compose -f "$COMPOSE_DIR/docker-compose.yml" pull
docker compose -f "$COMPOSE_DIR/docker-compose.yml" up -d

# --- Alloy 설정 반영 (bind-mount 변경은 up -d가 감지 못하므로 reload) ---
curl -sf -X POST http://localhost:12345/-/reload && echo "Alloy config reloaded" \
  || echo "WARN: Alloy reload 실패 (무시)" >&2

# --- .env 파일 삭제 (보안) ---
rm -f "$ENV_FILE"

# --- 결과 확인 ---
echo "배포 완료"
docker compose -f "$COMPOSE_DIR/docker-compose.yml" ps

# --- 헬스체크 ---
echo "헬스체크 대기 중..."
sleep 10

FAILED=0

# Redis Exporter 확인
if curl -sf http://localhost:9121/metrics | grep -q "redis_up"; then
  echo "Redis Exporter 정상"
else
  echo "Redis Exporter 응답 없음" >&2
  FAILED=1
fi

# Alloy 확인
if curl -sf http://localhost:12345/-/ready | grep -q "ready"; then
  echo "Alloy 정상"
else
  echo "Alloy 응답 없음" >&2
  FAILED=1
fi

if [ "$FAILED" = "1" ]; then
  echo "헬스체크 실패" >&2
  docker compose -f "$COMPOSE_DIR/docker-compose.yml" logs --tail 30
  exit 1
fi
